DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE IF NOT EXISTS hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    app       varchar(255)                   NOT NULL,
    uri       varchar(255)                   NOT NULL,
    ip        varchar(255)                   NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE    NOT NULL,
    CONSTRAINT hit_id_pk PRIMARY KEY (id)
    );

CREATE INDEX IF NOT EXISTS hits_timestamp_index ON hits (timestamp);
CREATE INDEX IF NOT EXISTS hits_uri_index ON hits (uri);
CREATE INDEX IF NOT EXISTS hits_app_index ON hits (app);
CREATE INDEX IF NOT EXISTS hits_ip_index ON hits (ip);